# **NumPy Array**

- NumPy / Numerical Python is a library that specialises in handling numerical data.
- With a regular Python list, we cannot perform element-wise operations.
- NumPy solves this problem by using NumPy array.

In [2]:
import numpy as np

In [3]:
heights = [1.73, 1.68, 1.71, 1.89]
weights = [68, 59.5, 80, 81.3]

In [4]:
np_heights = np.array(heights) #create a Numpy array from list
np_weights = np.array(weights)
np_bmi = np_weights / np_heights ** 2
print(np_bmi) #straightway calculate all the values in array

[22.72043837 21.08134921 27.35884546 22.75972117]


- Filter the np_bmi array using Boolean comparison

In [5]:
condition = np_bmi > 22
np_bmi[condition]

array([22.72043837, 27.35884546, 22.75972117])

In [6]:
#Another way of doing it
np_bmi[np_bmi > 22]

array([22.72043837, 27.35884546, 22.75972117])

***

## 2D NumPy Array 

In [7]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 68.2, 86.1, 96.3, 50.0]])
print(np_2d.shape) # Check the shape using the attributes (2 rows and 5 columns)

(2, 5)


**Subsetting NumPy array**

In [8]:
np_2d[0] #return first row, all column

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [9]:
np_2d[0][2] #return first row, third column

1.71

In [10]:
np_2d[0,2] #same like above, return first row, third column

1.71

In [11]:
np_2d[0, [0,2]] #return first row, first and third column

array([1.73, 1.71])

In [12]:
np_2d[:, 1:3] #return all rows, second and third column

array([[ 1.68,  1.71],
       [68.2 , 86.1 ]])

***

## Conditional Statements

### If-Elif-Else  
- If condition is met, then the portion of the code is executed.

In [13]:
z = 3

if z % 2 == 0: #If remainder of z/2 is zero
    print('z is divisible by 2')
elif z % 3 ==0: #If remainder of z/3 is zero
    print('z is divisible by 3')
else:
    print('z is not divisible by 2 or 3')

z is divisible by 3


### While loop
- while loop is a repeated if statement
- it will run as long as the condition is met
- have to be extra careful to avoid the while loop from running forever

In [14]:
counter = 5

while counter >= 0:
    print(counter)
    counter = counter - 1
print('.\n.\n.')
print('Up up and away')

5
4
3
2
1
0
.
.
.
Up up and away


### For loop
- for loop executes an expression for each element in a sequence
- useful when looping through a collection of elements such as in a list

In [15]:
family = ['father', 'mother', 'sister', 'brother', 'baby']

for siblings in family:
    print(siblings)

father
mother
sister
brother
baby


- using the enumerate function, we can print incremental index in a 'for' loop. 

In [16]:
for i, siblings in enumerate(family):
    print('{} {}'.format(i+1, siblings))

1 father
2 mother
3 sister
4 brother
5 baby


- for loop is also useful in printing dictionaries
- use the items() method on your dictionary

In [17]:
heights_dict = {'Yusuf':1.73, 'Fatimah':1.68, 'Aisyah':1.71, 'Ismail':1.89}
for k,v in heights_dict.items():
    print('{}\'s height is {}m'.format(k,v))

Yusuf's height is 1.73m
Fatimah's height is 1.68m
Aisyah's height is 1.71m
Ismail's height is 1.89m
